package cmd

import (
	"log/slog"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func init() {
	rootCmd.AddCommand(mangenCmd)
}

var mangenCmd = &cobra.Command{
	Use:   "mangen [dir]",
	Short: "generates a man (1) page for goje. in the given directory",
	Long:  "generates a man (1) page for goje. in the given directory. defaults to current directory",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		return writeManpages(rootCmd, args[0])
	},
}

func writeManpages(root *cobra.Command, dir string) error {
	date, err := time.Parse("2006-01", "2025-05")
	if err != nil {
		return err
	}

	header := &doc.GenManHeader{
		Title:   "goje",
		Section: "1",
		Source:  "generated by `goje mangen`",
		Date:    &date,
	}

	slog.Info("writing man pages to directory", "dir", dir)
	return doc.GenManTree(root, header, dir)
}
